/// Flutter icons JPlayer
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  JPlayer
///      fonts:
///       - asset: fonts/JPlayer.ttf
///
/// 
///
library;
import 'package:flutter/widgets.dart';

class JPlayer {
  JPlayer._();

  static const _kFontFam = 'JPlayer';
  static const String? _kFontPkg = null;

  static const IconData chevron_right = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData clock = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData close = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData download = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData like = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData list = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData log_out = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData mix = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData more_horizontal = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData music = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData next_track = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData play_circle_outlined = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData prev_track = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData repeat = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData search = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData settings = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData sliders = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData trash_2 = IconData(0xe811, fontFamily: _kFontFam);
}
